Title: "Python Workshop: Introduction to Python - Part I"

Author: "Dr. Armin Hatefi"

Date: "Monday, January 16, 2023"

**Note:** This content is protected and may not be shared, uploaded, or distributed.

# Outline:

- Basics of Datatypes, Jupyter and Python
- Basics of Python Programming

# About this Workshop

## High-level overview:
- This part of the workshop has a programming prerequisite.
- Therefore, this course does not start from "no programming knowledge".
  1. You should know what an `if` statement is.
  2. You should know what a `for` loop is.
  3. You should know what a `while` loop is.
  4. You should know what a function is.

# Basics of Datatypes, Jupyter and Python

## Common built-in Python data types

| Name | Type  | Description | Example |
| :--- | :--- | :--- | :--- |
| integer | `int` | positive/negative whole numbers | `42` |
| floating point number | `float` | real number in decimal form | `3.14159` |
| boolean | `bool` | true or false | `True` |
| string | `str` | text | `"Am I a cheezburger?"` |
| list | `list` | a collection of objects - mutable & ordered | `['Armin','Xinyi','Sarah', 'Python']` |
| tuple | `tuple` | a collection of objects - immutable & ordered | `('Thursday',2,22,2022)` |
| dictionary | `dict` | mapping of key-value pairs | `{'name':'DSCI','code': 6607,'building': 'mathematics'}` |
| none | `NoneType` | represents no value | `None` |

In [2]:
x = 42

In [3]:
type(x)

int

In [4]:
print(x)

42


In [5]:
x # in Jupyter we don't need to explicitly print for the last line of a cell

42

In [6]:
pi = 3.14159

In [7]:
print(pi)

3.14159


In [8]:
type(pi)

float

#### Arithmetic Operators

The syntax for the arithmetic operators are:

| Operator | Description |
| :---: | :---: |
| `+` | addition |
| `-` | subtraction |
| `*` | multiplication |
| `/` | division |
| `**` | exponentiation |
| `//` | integer division |
| `%`  | modulo |

Let's apply these operators to numeric types and observe the results.

In [9]:
1 + 2 + 3 + 4 + 5

15

In [10]:
2**10

1024

In [11]:
type(2**10)

int

In [12]:
type(2.0**10)

float

#### None

- `NoneType` is its own type in Python.
- It only has one possible value, `None`

In [13]:
x = None

In [14]:
print(x)

None


In [15]:
type(x)

NoneType

#### Strings

- Text is stored as a type called a string. 
- We think of a string as a sequence of characters. 
- We write strings as characters enclosed with either:
  - single quotes, e.g., `'Hello'` 
  - double quotes, e.g., `"Goodbye"`
  - triple single quotes, e.g., `'''Yesterday'''`
  - triple double quotes, e.g., `"""Tomorrow"""`

If the string contains a quotation or apostrophe, we can use double quotes or triple quotes to define the string.

In [16]:
sentence = "It's a rainy day."

In [17]:
print(sentence)

It's a rainy day.


In [18]:
type(sentence)

str

#### Boolean

- The Boolean (`bool`) type has two values: `True` and `False`. 

In [19]:
the_truth = True

In [20]:
print(the_truth)

True


In [21]:
type(the_truth)

bool

In [22]:
lies = False

In [23]:
print(lies)

False


In [24]:
type(lies)

bool

#### Comparison Operators

Compare objects using comparison operators. The result is a Boolean value.

| Operator | Description |
| :---: | :--- |
| `x == y ` | is `x` equal to `y`? |
| `x != y` | is `x` not equal to `y`? |
| `x > y` | is `x` greater than `y`? |
| `x >= y` | is `x` greater than or equal to `y`? |
| `x < y` | is `x` less than `y`? |
| `x <= y` | is `x` less than or equal to `y`? |
| `x is y` | is `x` the same object as `y`? |

In [25]:
2 < 3

True

In [26]:
"Data Science" != "everything"

True

Operators on Boolean values.

| Operator | Description |
| :---: | :--- |
|`x and y`| are `x` and `y` both true? |
|`x or y` | is at least one of `x` and `y` true? |
| `not x` | is `x` false? | 

In [27]:
True and True

True

In [28]:
True and False

False

In [29]:
False or False

False

In [30]:
("Python 2" != "Python 3") and (2 <= 3)

True

In [31]:
not True

False

In [32]:
not not True

True

## Data Structures and Sequences

- Python’s data structures are simple but powerful. 
- Mastering their use is a critical part of becoming a proficient Python programmer. 
- We start with tuple, list, and dictionary, which are some of the most frequently used sequence types.

## Tuples

- A tuple is an **ordered**, **immutable** sequence of Python objects which, once assigned, cannot be changed. 
- The easiest way to create one is with a comma-separated sequence of values wrapped in parentheses:

In [33]:
tup = 4,5,6

In [34]:
len(tup)

3

In [35]:
tup

(4, 5, 6)

In [36]:
type(tup)

tuple

In [37]:
tup2 = (4,5,6)

In [38]:
tup == tup2

True

In [39]:
nested_tup = (4, 5, 6), (7, 8)

In [40]:
nested_tup

((4, 5, 6), (7, 8))

In [41]:
len(nested_tup)

2

In [42]:
tup = tuple('string')

In [43]:
tup

('s', 't', 'r', 'i', 'n', 'g')

Elements can be accessed with square brackets `[]` as with most other sequence types. As in `C`, `C++`, `Java`, and many other languages, sequences are *0-indexed* in Python:

In [44]:
tup[0]

's'

In [45]:
tup[1]

't'

In [46]:
nested_tup[0]

(4, 5, 6)

In [47]:
nested_tup[1]

(7, 8)

While the objects stored in a tuple may be mutable themselves, once the tuple is created it’s not possible to modify which object is stored in each slot:

In [48]:
tup[1] = 'p'

TypeError: 'tuple' object does not support item assignment

In [49]:
tup = tuple(['foo', [1, 2], True])

In [50]:
tup.append(False)

AttributeError: 'tuple' object has no attribute 'append'

In [51]:
tup[2] = False

TypeError: 'tuple' object does not support item assignment

Since the size and contents of a tuple cannot be modified, it is very light on instance methods. A particularly method  (also available on lists) is *count*, which counts the number of occurrences of a value:

In [52]:
a = (1, 2, 2, 2, 3, 4, 2)

In [53]:
a.count(2)

4

## List
In contrast with tuples, lists are **ordered** and mutable, where length their contents can be modified in place.  You can define them using square brackets `[]` or using the `list` type function:

In [54]:
my_list = [1, 2, "THREE", 4, 0.5, None]

In [55]:
print(my_list)

[1, 2, 'THREE', 4, 0.5, None]


In [56]:
my_list[0]

1

In [57]:
type(my_list[2])

str

In [58]:
type(my_list)

list

In [59]:
len(my_list)

6

In [60]:
tup = ("foo", "bar", "baz")

In [61]:
list(tup)

['foo', 'bar', 'baz']

In [62]:
gen = range(10)

In [63]:
gen

range(0, 10)

In [64]:
list(gen)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## Adding and removing elements
Elements can be appended to the end of the list with the `append` method:

In [65]:
b_list = ['foo', 'peekaboo', 'baz']
?b_list.append

In [66]:
b_list.append("dwarf")
b_list

['foo', 'peekaboo', 'baz', 'dwarf']

Using `insert` you can insert an element at a specific location in the list:

In [67]:
b_list.insert(2, "red")
b_list

['foo', 'peekaboo', 'red', 'baz', 'dwarf']

The inverse operation to insert is `pop`, which removes and returns an element at a particular index:

In [68]:
b_list.pop(2)

'red'

In [69]:
b_list

['foo', 'peekaboo', 'baz', 'dwarf']

Check if a list contains a value using the in keyword:

If you have a list already defined, you can append multiple elements to it using the extend method:

In [70]:
x = [4, None, "foo"]

In [71]:
x.extend([7, 8, (2, 3)])

In [72]:
x

[4, None, 'foo', 7, 8, (2, 3)]

## Sorting
You can sort a list in place (without creating a new object) by calling its `sort` function:

In [73]:
a = [7, 2, 5, 1, 3]

In [74]:
sorted(a)

[1, 2, 3, 5, 7]

In [75]:
a.sort()

In [76]:
a

[1, 2, 3, 5, 7]

## Slicing
You can select sections of most sequence types by using slice notation, which in its basic form consists of `start:stop` passed to the indexing operator `[]`:

In [77]:
seq = [7, 2, 3, 7, 5, 6, 0, 1]

In [78]:
seq[1:5]

[2, 3, 7, 5]

Slices can also be assigned with a sequence:

In [79]:
seq[3:5] = [6, 3]
seq

[7, 2, 3, 6, 3, 6, 0, 1]

- While the element at the start index is included, the stop index is not included, so that the number of elements in the result is `stop - start`.

- Either the `start` or `stop` can be omitted, in which case they default to the start of the sequence and the end of the sequence.

In [80]:
seq[:5]

[7, 2, 3, 6, 3]

In [81]:
seq[3:]

[6, 3, 6, 0, 1]

Negative indices slice the sequence relative to the end:

In [82]:
seq[-4]

3

A `step` can also be used after a second colon to, say, take every other element:

In [83]:
seq[::2]

[7, 3, 3, 0]

In [84]:
seq[::-1]

[1, 0, 6, 3, 6, 3, 2, 7]

## Dictionary
- The  `dict` may be the most important built-in Python data structure. 
- A dictionary stores a collection of key-value pairs, where key and value are Python objects. 
- Each key is associated with a value so that a value can be conveniently retrieved, inserted, modified, or deleted given a particular key. 
- We can also edit dictionaries (they are mutable):
- One approach for creating a dictionary is to use curly braces {} and colons to separate keys and values:

In [85]:
empty_dict = {}

In [86]:
d1 = {"a": "some value", "b": [1, 2, 3, 4]}

In [87]:
d1

{'a': 'some value', 'b': [1, 2, 3, 4]}

You can access, insert, or set elements using the same syntax as for accessing elements of a list or tuple:

In [88]:
d1[7] = "an integer"

In [89]:
d1

{'a': 'some value', 'b': [1, 2, 3, 4], 7: 'an integer'}

In [90]:
d1["b"]

[1, 2, 3, 4]

In [91]:
d1["b"] = 'Jack'

In [92]:
d1

{'a': 'some value', 'b': 'Jack', 7: 'an integer'}

You can check if a dictionary contains a key using the same syntax used for checking whether a list or tuple contains a value:

In [93]:
"b" in d1

True

In [94]:
"a" in d1.keys()

True

In [95]:
"Jack" in d1.values()

True

You can delete values using either the `del` keyword. 

In [96]:
d1[5] = "some value"
d1

{'a': 'some value', 'b': 'Jack', 7: 'an integer', 5: 'some value'}

In [97]:
d1["dummy"] = "another value"
d1

{'a': 'some value',
 'b': 'Jack',
 7: 'an integer',
 5: 'some value',
 'dummy': 'another value'}

In [98]:
del d1[5]
d1

{'a': 'some value', 'b': 'Jack', 7: 'an integer', 'dummy': 'another value'}

In [99]:
list(d1.keys())

['a', 'b', 7, 'dummy']

In [100]:
list(d1.values())

['some value', 'Jack', 'an integer', 'another value']

## Set
- A set is an `unordered` collection of unique elements. 
- A set can be created in two ways: via the `set` function or via a `set literal` with curly braces:

In [101]:
set([2, 2, 2, 1, 3, 3])

{1, 2, 3}

In [102]:
{2, 2, 2, 1, 3, 3}


{1, 2, 3}

Sets support mathematical **set operations** like union, intersection, difference, and symmetric difference. Consider these two example sets:

In [103]:
a = {1, 2, 3, 4, 5}
b = {3, 4, 5, 6, 7, 8}

The union of these two sets is the set of distinct elements occurring in either set. This can be computed with either the `union` method or the `|` binary operator:

In [104]:
a.union(b)

{1, 2, 3, 4, 5, 6, 7, 8}

In [105]:
a | b

{1, 2, 3, 4, 5, 6, 7, 8}

In [106]:
a.intersection(b)

{3, 4, 5}

In [107]:
a & b

{3, 4, 5}

In [108]:
type(a)

set

In [109]:
list(a)

[1, 2, 3, 4, 5]

In [110]:
my_list = [1, 2, 2, 3, 4]
my_list

[1, 2, 2, 3, 4]

In [111]:
my_tuple2 = tuple(my_list)
my_tuple2

(1, 2, 2, 3, 4)

In [112]:
my_tuple

NameError: name 'my_tuple' is not defined

In [113]:
list(my_tuple)

NameError: name 'my_tuple' is not defined

Sets are equal if and only if their contents are equal:

In [114]:
{1, 2, 3} == {3, 2, 1}

True

## Strings
Strings behave the same as lists and tuples when it comes to indexing and slicing.

In [115]:
alphabet = "abcdefghijklmnopqrstuvwxyz"

In [116]:
alphabet[0]

'a'

In [117]:
alphabet[-2]

'y'

In [118]:
alphabet[:5]

'abcde'

- Strings and tuples are immutable types which means they cannot be modified. 

In [119]:
my_name = "Armin"

In [120]:
my_name[-2] = 'e'

TypeError: 'str' object does not support item assignment

#### String formatting
Old formatting style (borrowed from the C programming language):

In [121]:
template = "Hello, my name is %s. I am %.2f years old."

In [122]:
template % ("Tesla", 10/4)

'Hello, my name is Tesla. I am 2.50 years old.'

In [123]:
template_new = "Hello, my name is {}. I am {:.2f} years old."

In [124]:
template_new.format("Tesla", 10/4)

'Hello, my name is Tesla. I am 2.50 years old.'

Newer formatting style (see [here](https://realpython.com/python-f-strings/#f-strings-a-new-and-improved-way-to-format-strings-in-python)) - note the `f` before the start of the string:

In [125]:
name = "Tesla"
age = 10/4
template_new = f'Hello, my name is {name}. I am {age:.2f} years old.'
template_new

'Hello, my name is Tesla. I am 2.50 years old.'

The main points to notice:

* Use keywords `if`, `elif` and `else`
* The colon `:` ends each conditional expression
* Indentation (by 4 empty space) defines code blocks
* In an `if` statement, the first block whose conditional statement returns `True` is executed and the program exits the `if` block
* `if` statements don't necessarily need `elif` or `else`
* `elif` lets us check several conditions
* `else` lets us evaluate a default block if all other conditions are `False`
* the end of the entire `if` statement is where the indentation returns to the same level as the first `if` keyword

In [126]:
x = 6

In [127]:
if x < 0:
    print("It's negative")
elif x == 0:
    print("Equal to zero")
elif 0 < x < 5:
    print("Positive but smaller than 5")
else:
    print("Positive and larger than or equal to 5")

Positive and larger than or equal to 5


- With a compound condition using `and` or `or`, conditions are evaluated left to right:

In [128]:
a = 5; b = 7
c = 8; d = 4

In [129]:
if a < b or c > d:
    print("Made it")


Made it


In this example, the comparison `c > d` never gets evaluated because the first comparison was `True`.


## For loops


The main points to notice:

- Keyword for begins the loop
- Colon : ends the first line of the loop
- We can iterate over any kind of iterable: list, tuple, range, string. In this case, we are iterating over the values in a list
- Block of code indented is executed for each value in the list (hence the name "for" loops, sometimes also called "for each" loops)
- The loop ends after the variable n has taken all the values in the list

In [130]:
sequence = [1, 2, 0, 4, 6, 5, 2, 1]

In [131]:
total_until_5 = 0

In [132]:
for value in sequence:
    if value == 5:
        break
    total_until_5 += value
    print(total_until_5)

1
3
3
7
13


In [133]:
total_until_5

13

## range
The `range` function generates a sequence of evenly spaced integers:

In [134]:
range(10)

range(0, 10)

In [135]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

- As you can see, `range` produces integers up to but not including the endpoint. 
- A common use of range is for iterating through sequences by index:

In [136]:
for i in seq:
    print(f"element {i}: {seq[i]}")

element 7: 1
element 2: 3
element 3: 6
element 6: 0
element 3: 6
element 6: 0
element 0: 7
element 1: 2


In [137]:
seq = [1, 2, 3, 4]
for i in range(len(seq)):
    print(f"element {i}: {seq[i]}")

element 0: 1
element 1: 2
element 2: 3
element 3: 4


In [138]:
for x in [1,2,3]:
    for y in ["a","b","c"]:
        print((x,y))

(1, 'a')
(1, 'b')
(1, 'c')
(2, 'a')
(2, 'b')
(2, 'c')
(3, 'a')
(3, 'b')
(3, 'c')


## while loops
A `while` loop specifies a condition and a block of code that is to be executed until the condition evaluates to `False` or the loop is explicitly ended with `break`:

In [139]:
x = 256
total = 0
while x > 0:
    if total > 500:
        break
    total += x
    x = x // 2
    print((total,x))

(256, 128)
(384, 64)
(448, 32)
(480, 16)
(496, 8)
(504, 4)


## Functions Intro

- Define a **function** to re-use a block of code with different input parameters, also known as **arguments**. 
- For example, define a function called `square_fun` which takes one input parameter `n` and returns the square `n**2`.

In [140]:
def square_fun(n):
    n_squared = n**2
    return n_squared

In [141]:
square_fun(6)

36

- Begins with `def` keyword, function name, input parameters and then colon (`:`)
- Function block defined by indentation
- Output or "return" value of the function is given by the `return` keyword

There is no issue with having multiple `return` statements. 

In [142]:
def my_function2(x, y):
    if x > y:
        return  x - y
    else:
        return  x + y

In [143]:
my_function2(3.14, 7)

10.14

In [144]:
def repeat_string(s, n=2):
    return s*n

In [145]:
repeat_string("stat",3)

'statstatstat'

In [146]:
repeat_string("stat") # do not specify `n`; it is optional

'statstat'

## Lambda Functions 

Python has support for so-called anonymous or lambda functions, which are a way of writing functions consisting of a single statement, the result of which is the return value.

In [147]:
def short_function(x):
    return x * 2

In [148]:
equiv_anon = lambda x: x * 2

In [149]:
equiv_anon(2)

4

In [150]:
def apply_to_list(some_list, f):
    return [f(x) for x in some_list]

In [151]:
ints = [4, 0, 1, 5, 6]

In [152]:
apply_to_list(ints, lambda x: x * 2)

[8, 0, 2, 10, 12]

In [153]:
def add_numbers(x,y):
    return x + y

In [154]:
add_five = lambda y: add_numbers(5,y)

In [155]:
add_five(12)

17

In [156]:
def add_five2(y):
    d = add_numbers(5, y)
    return(d)

In [157]:
add_five2(12)

17

In [158]:
def add_five3(x,f):
    d = f(5,x)
    return(d)

In [159]:
add_five3(x=12,f=add_numbers)

17

## Numpy Arrays

In [160]:
import numpy as np

A numpy array is sort of like a list:

In [161]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [162]:
my_tuple = (1,2,3,4,5)
my_tuple

(1, 2, 3, 4, 5)

In [163]:
my_array = np.array((1,2,3,4,5))
my_array

array([1, 2, 3, 4, 5])

In [164]:
type(my_array)

numpy.ndarray

In [165]:
my_array_from_tuple = np.array(my_tuple)
my_array_from_tuple

array([1, 2, 3, 4, 5])

In [166]:
my_array_from_list = np.array(my_list)
my_array_from_list

array([1, 2, 3, 4, 5])

However, unlike a list, it can only hold a single type (usually numbers):

In [167]:
my_list = [1,"hi"]

In [168]:
my_array = np.array((1, "hi"))

In [169]:
my_array

array(['1', 'hi'], dtype='<U21')

Above: it converted the integer `1` into the string `'1'` (just avoid this!).

`numpy.arange` is an array-valued version of the built-in Python `range` function:

In [170]:
x = np.arange(1,5) # from 1 inclusive to 5 exlcusive
x

array([1, 2, 3, 4])

In [171]:
x = np.arange(1,5,0.5) # step by 0.5
x

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [172]:
x = np.linspace(1,5,20) # 20 equally spaced points between 1 and 5
x

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

The `numpy.random` module supplements the built-in Python random module with functions for efficiently generating whole arrays of sample values from many kinds of probability distributions. For list of distributions, see [Random Sampling](https://numpy.org/doc/stable/reference/random/generator.html)

In [173]:
x = np.random.randn(5) # random numbers uniformly distributed from 0 to 1
x

array([-0.67828281, -0.36544281, -1.99759183,  1.38441686, -0.9692205 ])

In [174]:
xx = np.random.normal(loc=2.0, scale=1,size=10)
xx

array([2.12250684, 1.31139242, 1.76943725, 2.29263319, 2.44464223,
       1.38331453, 1.730934  , 2.64136032, 2.51407622, 3.49906255])

### Elementwise Operations

In [175]:
x = np.ones(4)
x

array([1., 1., 1., 1.])

In [176]:
y = x + 1
y

array([2., 2., 2., 2.])

In [177]:
x - y

array([-1., -1., -1., -1.])

In [178]:
x == y

array([False, False, False, False])

## Array Shapes

The above are 1-D arrays:

In [179]:
x = np.random.rand(2,4)
x

array([[0.25388233, 0.00570233, 0.98952171, 0.57588715],
       [0.69229435, 0.65720123, 0.16180622, 0.05494227]])

In [180]:
x.shape

(2, 4)

In [181]:
x.size # total number of elements

8

In [182]:
x.ndim # len(x.shape)

2

**One of the most confusing things about numpy:** what I call a "1-D array" can have 3 possible shapes:

In [183]:
x = np.ones(5)
print(x)
print("size:", x.size)
print("ndim:", x.ndim)
print("shape:",x.shape)

[1. 1. 1. 1. 1.]
size: 5
ndim: 1
shape: (5,)


In [184]:
y = np.ones((1,5))
print(y)
print("size:", y.size)
print("ndim:", y.ndim)
print("shape:",y.shape)

[[1. 1. 1. 1. 1.]]
size: 5
ndim: 2
shape: (1, 5)


In [185]:
z = np.ones((5,1))
print(z)
print("size:", z.size)
print("ndim:", z.ndim)
print("shape:",z.shape)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
size: 5
ndim: 2
shape: (5, 1)


## Indexing and Slicing

In [186]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [187]:
x[3]

3

In [188]:
x[1:4:2]

array([1, 3])

In [189]:
x = np.arange(20).reshape(5,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [190]:
x[3,1] # do this

13

In [191]:
x[3][1] # i do not like this as much

13

In [192]:
x[3]

array([12, 13, 14, 15])

In [193]:
len(x) # generally, just confusing

5

In [194]:
x.shape

(5, 4)

In [195]:
x[:,1] # column number 2

array([ 1,  5,  9, 13, 17])

In [196]:
x[3,:]

array([12, 13, 14, 15])

In [197]:
x[3:,:4]

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

In [198]:
x.T

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

When doing matrix computations, you may do this very often—for example, when computing the inner matrix product using `numpy.dot`:

In [199]:
y1 = np.random.randint(20,size=(4,5))
y1

array([[ 0,  5, 17,  3, 13],
       [ 4,  2, 18, 16, 18],
       [15,  2, 13,  9,  9],
       [ 4,  3, 18, 17,  8]])

In [200]:
x.T

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [201]:
np.dot(x,y1)

array([[  46,   15,   98,   85,   60],
       [ 138,   63,  362,  265,  252],
       [ 230,  111,  626,  445,  444],
       [ 322,  159,  890,  625,  636],
       [ 414,  207, 1154,  805,  828]])

The `@` infix operator is another way to do matrix multiplication:

In [202]:
 y1.T @ y1

array([[ 257,   50,  339,  267,  239],
       [  50,   42,  201,  116,  143],
       [ 339,  201, 1106,  762,  806],
       [ 267,  116,  762,  635,  544],
       [ 239,  143,  806,  544,  638]])

## Mathematical and Statistical Methods

In [203]:
x = np.random.randn(5)
x

array([-0.2394111 ,  0.41608161,  2.62176887,  1.35642708, -0.57267512])

In [204]:
x.max()

2.621768871368737

In [205]:
x.min()

-0.5726751200516698

In [206]:
x.argmax()

2

In [207]:
x.argsort()

array([4, 0, 1, 3, 2])

In [208]:
x[x.argsort()]

array([-0.57267512, -0.2394111 ,  0.41608161,  1.35642708,  2.62176887])

In [209]:
x.cumsum()

array([-0.2394111 ,  0.17667051,  2.79843938,  4.15486647,  3.58219135])

In [210]:
abs(x)

array([0.2394111 , 0.41608161, 2.62176887, 1.35642708, 0.57267512])

In [211]:
x = np.random.randint(12,size=(4,3))
x

array([[ 9,  7,  6],
       [ 4,  0,  8],
       [ 5,  2,  1],
       [ 2, 11,  1]])

In [212]:
x.mean()

4.666666666666667

In [213]:
x.var()

11.722222222222223

In [214]:
x.mean(axis=0) # axis = 0 means along the column and axis = 1 means working along the row

array([5., 5., 4.])

In [215]:
np.sort(x,axis=0)

array([[ 2,  0,  1],
       [ 4,  2,  1],
       [ 5,  7,  6],
       [ 9, 11,  8]])

In [216]:
x

array([[ 9,  7,  6],
       [ 4,  0,  8],
       [ 5,  2,  1],
       [ 2, 11,  1]])